# Generated by Django 4.1 on 2024-07-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../defaultusericon_afo27r', upload_to='images/'),
        ),
    ]
