# Generated by Django 3.2.25 on 2024-06-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
    ]
