# Generated by Django 4.1 on 2024-07-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
