# Generated by Django 4.1 on 2024-07-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='../clapper_board_vector_oi5zxv', upload_to='images/'),
        ),
    ]
